user      = "root"
password  = ""
host      = "127.0.0.1"
port      = 3306
dialect   = "mysql"
database  = "employees"
threshold = 60

[ignore]
departments = ["dept_no"]
employees = ["emp_no", "birth_date"]
